### ISSUE TITLE
error trying to build

### ISSUE THREAD

**Issue by schmotz** [sjkp/powerbi-cors-app-ts#1]
I get the following error when running "gulp build".  I'm not sure what the problem is.  

C:\dev_downloads\test2\powerbi-cors-app-ts>gulp build
[10:27:49] Using gulpfile C:\dev_downloads\test2\powerbi-cors-app-ts\gulpfile.js

[10:27:49] Starting 'tsbuild'...
[10:27:49] Starting 'tsconfig'...
[10:27:49] Finished 'tsconfig' after 98 ms
[10:27:49] Starting 'tscompile'...
Warning: gulp-run is deprecated
[10:27:49] 'tscompile' errored after 59 ms
[10:27:49] Error: Command `tsc` exited with code 5
    at ChildProcess.<anonymous> (C:\dev_downloads\test2\powerbi-cors-app-ts\node
_modules\gulp-run\lib\command.js:147:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
[10:27:49] 'tsbuild' errored after 165 ms
[10:27:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'tscompile'.
$ tsc
Version 1.4.0.0

**Comment by sjkp** [comment]
Probably i used a newer typescript compiler version, if im not mistaken 1.5
